name: 'Clear action cache'
description: 'As suggested by GitHub to prevent low disk space: https://github.com/ahttps://github.com/flyteorg/flyte/issues/new/choose site'
  steps:
    - shell: bash
      run: |
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc
        rm -rf "/usr/local/share/boost"
        rm -rf "$AGENT_TOOLSDIRECTORY"
